sudo: required

cache:
  yarn: true
  directories:
    - node_modules
    - test_project/node_modules

env:
  - TOXENV=py36

install: pip install -U tox

language: python

python: 3.6

before_install:
  - .travis/docker.sh
  - .travis/yarn.sh
  - docker-compose up -d webserver selenium
  - /bin/bash -c "while ! nc -z localhost 44444; do echo Waiting for selenium to start; sleep 1; done;"
  - /bin/bash -c "while ! nc -z localhost 9080; do echo Waiting for nginx to start; sleep 1; done;"
  - /usr/bin/yarn --version

before_script:
  - cd reciprocity/static/reciprocity/js/tests && /usr/bin/yarn --dev
  - pwd
  - cd test_project && /usr/bin/yarn --dev

script:
  - tox -e ${TOXENV}
