sudo: required

env:
  - TOXENV=py36

install: pip install -U tox

language: python

python: 3.6

before_install:
  - .travis/main.sh
  - docker version

script:
  - docker-compose up -d webserver selenium
  - /bin/bash -c "while ! nc -z localhost 44444; do echo Waiting for selenium to start; sleep 1; done;"
  - /bin/bash -c "while ! nc -z localhost 9080; do echo Waiting for nginx to start; sleep 1; done;"    
  - tox -e ${TOXENV}
