version: '2'
services:

  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 4M
    restart: on-failure

  webserver:
    build:
      dockerfile: Dockerfile-nginx
      context: docker
    ports:
      - "9080:80"
    depends_on:
      - dockerhost

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "45672:5672"

  selenium:
    image: selenium/standalone-firefox-debug
    ports:
      - "44444:4444"
      - "45900:5900"
    depends_on:
      - webserver
