version: '2'
services:

  webserver:
    build:
      dockerfile: Dockerfile-nginx
      context: docker
    ports:
      - "9080:80"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "45672:5672"

  selenium:
    image: selenium/standalone-firefox-debug
    ports:
      - "44444:4444"
      - "45900:5900"
